.POSIX:

# This Makefile was generated by maje
# See https://src.kaivo.net/dev/maje/ for more information
# Do not edit this Makefile by hand

CC=c99
LD=$(CC)
CFLAGS=-Wall -Wextra -Wpedantic -Werror -g
LDFLAGS=
LDLIBS=
SRCDIR=.
OBJDIR=.
BINDIR=$(OBJDIR)
LIBDIR=$(OBJDIR)
DESTDIR=/usr/local

all: $(BINDIR)/cc

clean:
	rm -f $(BINDIR)/cc $(OBJDIR)/*.o

install: $(BINDIR)/cc
	mkdir -p $(DESTDIR)/bin
	cp $(BINDIR)/cc $(DESTDIR)/bin

$(BINDIR)/cc: $(OBJDIR)/cc.o
$(OBJDIR)/cc.o: $(SRCDIR)/cc.h
$(OBJDIR)/cc.o: $(SRCDIR)/cc.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/cc.c

$(BINDIR)/cc: $(OBJDIR)/link.o
$(OBJDIR)/link.o: $(SRCDIR)/link.h
$(OBJDIR)/link.o: $(SRCDIR)/link.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/link.c

$(BINDIR)/cc: $(OBJDIR)/cpp.o
$(OBJDIR)/cpp.o: $(SRCDIR)/cc.h
$(OBJDIR)/cpp.o: $(SRCDIR)/cpp.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/cpp.c

$(BINDIR)/cc:
	@mkdir -p $(@D)
	$(LD) $(LDFLAGS) -o $@ $(OBJDIR)/*.o $(LDLIBS)
